import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "next-themes";
import SmokeyCursor from "@/components/lightswind/smokey-cursor";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} 
  
    antialiased
  `}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SmokeyCursor className='' autoColors={false} colorUpdateSpeed={0}  
/>
    
     <div className="flex h-screen flex-col   bg-white text-black
    dark:bg-black dark:text-white data-cursor-target">
        <Navbar/>
      <main className="flex-1">{children}</main>

        </div>
        </ThemeProvider>
   
        
      </body>
    </html>
  );
}
